Portfolio Project Mobile Home
demesameneshoa/Portfolio pull request #2
Opened 2023-04-27 21:46 UTC by demesameneshoa

- Added the Index.html and style.css file as per the requirement
- Added the necessary images and icons
- Added all the colors and font specifications

2023-04-27 23:37 UTC, ademibowale requested changes
# Required Changes 🔁
# Hello @demesameneshoa     😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

![just a little bit](https://user-images.githubusercontent.com/92458236/184504866-f1a3e9e9-9072-441d-8ed3-27d483ba70d8.gif)

## Highlights

   ✅Correct use of Github Flow
  ✅ No linter errors
✅ Descriptive Pull Request
  

## Required Changes ♻️





_Check the comments under the review._




## Optional suggestions 
   
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 23:37 UTC, ademibowale commented on index.html
> +		</h1>
- [x] I would kindly suggest you create a seperate div tag for your `<h1>`tag  wrapp the `<h1>`tag in a `<div>`tag so that it will be easier for you to style, the <div> element makes it easier to target just certain parts of your webpage when you want to change the way they look or do something to them also a `<div>`tag is a container for HTML elements which is used to group elements together and apply styles to them.
- [ ] I would suggest you to work on your website user interface to be responsive  Minimum mobile screen size should be 375px. mobile version should be responsive until the desktop screen size.
- [ ] I would kindly suggest you to stick to the figma design as the exact copy of Figma
- [ ] Kindly work on font size and the font weight al make it align to be exact like figma template design
- [ ] Your Design
- [ ] ![template wrong 3](https://user-images.githubusercontent.com/92458236/235011935-a2945205-7762-4989-8a46-077279ab4a70.jpg)

- [ ] Figma Design
![figma templ3](https://user-images.githubusercontent.com/92458236/235012010-a1683315-3dec-439c-be21-008bb2eeec20.jpg)

2023-04-27 23:37 UTC, ademibowale commented on index.html
> +		</p>
- [x] I would kindly suggest you to create `<div>`tag for your `<p>`tag as well,this will make your code semantic and easy to read, a`<div>`tag is a container for HTML elements which is used to group elements together and apply styles to them,please fix this.  
- [ ] I  would kindly suggest you to work on  that your PR title and summary are not descriptive enought ,a PR title should be a brief description ofwhat your project is all about and the PR summary should tell all  what you have done or implement on your project please kindly fix that.

2023-04-28 08:19 UTC, demesameneshoa commented
- Enclosed H1 and P section of headline with div as per the request of the code review
- Edited the Pull request description
- Changed the Minimum Width property 375 Pixels
- Switched Fonts type and size as per the figma requirement

2023-04-28 08:47 UTC, OyePriscilla requested changes
Hi @demesameneshoa , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Used flexbox to place elements in the page ✔️
Implement the headline section of a personal portfolio site ✔️
Use images and backgrounds to enhance the look of the website ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 08:47 UTC, OyePriscilla commented on style.css
> +}
- [ ] As pointed out earlier, kindly ensure that your design is a close replica of the given template. 👍 As developers, it's always good that we pay attention to details; recruiters out there watch out for this. ℹ️ 

> |     | Your Design                                  | Figma Design                                  |     |
> | --- | ----------------------------------------------- | ------------------------------------------------ | --- |
> |     | <img width="282" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/235100218-59eadf4e-f79e-44d6-82e3-18c2f82103e7.png"> | <img width="227" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/235099869-acb4bf25-e496-4361-a878-027210826f4d.png"> |

2023-04-28 15:58 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @demesameneshoa 

Your project is complete! Great job  🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- figma design followed
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 15:58 UTC, tufoinnkuo10 commented on index.html
> +			Hey there.<br/>I'm Demes.<br/>
- [optional] please kindly add paddings and line spacing to the different elements of your headline, so they can follow the Figma version. Also ensure the social icons go down a little like in the original version. Like the previous reviewer noted, paying attention to details matters to the recruiters. Keep up the spirit 😄

2023-04-28 16:02 UTC, merged